Repository hackprot0/language-translation, pull requests merged in 2022-10, with the labels that each got.

#7 MohanCipher.py
  EncryptionCipher.py
Labels: hacktober, hacktoberfest, hacktoberfest-accepted

#8 Database having translations for sentences from English to Hindi
  data/eng-hin-db.txt
  data/notebook/data_gen.ipynb
  data/tf_uinittest.py
  setup_file.py
Labels: enhancement, good first issue, hacktober, hacktoberfest, hacktoberfest-accepted

#1 Integration test tf1.14 modules
  data/tf_uinittest.py
Labels: hacktober, hacktoberfest2021, hacktoberfest-accepted

#9 A program with a nice UI to implement and study DEA with different hyper parameters.
  Des.Js
  des.css
  des.js
  des_pa1.html
  hget.py
Labels: help wanted, hacktober, hacktoberfest, hacktoberfest-accepted

#10 Standard Blowfish Implementation
  BlowfishOBB.cpp
Labels: good first issue, hacktober, hacktoberfest, hacktoberfest-accepted

#11 Online voting
  blindVoting.py
Labels: good first issue, hacktober, hacktoberfest, hacktoberfest-accepted
